/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedFinanceReportsRouteImport } from './routes/_authenticated/finance.reports'
import { Route as AuthenticatedFinanceIncomeRouteImport } from './routes/_authenticated/finance.income'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated/finance.expenses'
import { Route as AuthenticatedFinanceCategoriesRouteImport } from './routes/_authenticated/finance.categories'
import { Route as AuthenticatedFinanceCashFlowRouteImport } from './routes/_authenticated/finance.cash-flow'
import { Route as AuthenticatedFinanceBudgetsRouteImport } from './routes/_authenticated/finance.budgets'
import { Route as AuthenticatedFinanceBillsRouteImport } from './routes/_authenticated/finance.bills'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedFinanceReportsRoute =
  AuthenticatedFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceIncomeRoute =
  AuthenticatedFinanceIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCategoriesRoute =
  AuthenticatedFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCashFlowRoute =
  AuthenticatedFinanceCashFlowRouteImport.update({
    id: '/cash-flow',
    path: '/cash-flow',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBudgetsRoute =
  AuthenticatedFinanceBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBillsRoute =
  AuthenticatedFinanceBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/finance/bills': typeof AuthenticatedFinanceBillsRoute
  '/_authenticated/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/_authenticated/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/_authenticated/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/income': typeof AuthenticatedFinanceIncomeRoute
  '/_authenticated/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/finance/bills'
    | '/finance/budgets'
    | '/finance/cash-flow'
    | '/finance/categories'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/reports'
    | '/projects/$projectId'
    | '/clients/'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/finance/bills'
    | '/finance/budgets'
    | '/finance/cash-flow'
    | '/finance/categories'
    | '/finance/expenses'
    | '/finance/income'
    | '/finance/reports'
    | '/projects/$projectId'
    | '/clients'
    | '/finance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calendar'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/finance/bills'
    | '/_authenticated/finance/budgets'
    | '/_authenticated/finance/cash-flow'
    | '/_authenticated/finance/categories'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/income'
    | '/_authenticated/finance/reports'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/clients/'
    | '/_authenticated/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/finance/reports': {
      id: '/_authenticated/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AuthenticatedFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/income': {
      id: '/_authenticated/finance/income'
      path: '/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof AuthenticatedFinanceIncomeRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/categories': {
      id: '/_authenticated/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof AuthenticatedFinanceCategoriesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/cash-flow': {
      id: '/_authenticated/finance/cash-flow'
      path: '/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof AuthenticatedFinanceCashFlowRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/budgets': {
      id: '/_authenticated/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AuthenticatedFinanceBudgetsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/bills': {
      id: '/_authenticated/finance/bills'
      path: '/bills'
      fullPath: '/finance/bills'
      preLoaderRoute: typeof AuthenticatedFinanceBillsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceBillsRoute: typeof AuthenticatedFinanceBillsRoute
  AuthenticatedFinanceBudgetsRoute: typeof AuthenticatedFinanceBudgetsRoute
  AuthenticatedFinanceCashFlowRoute: typeof AuthenticatedFinanceCashFlowRoute
  AuthenticatedFinanceCategoriesRoute: typeof AuthenticatedFinanceCategoriesRoute
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinanceIncomeRoute: typeof AuthenticatedFinanceIncomeRoute
  AuthenticatedFinanceReportsRoute: typeof AuthenticatedFinanceReportsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceBillsRoute: AuthenticatedFinanceBillsRoute,
  AuthenticatedFinanceBudgetsRoute: AuthenticatedFinanceBudgetsRoute,
  AuthenticatedFinanceCashFlowRoute: AuthenticatedFinanceCashFlowRoute,
  AuthenticatedFinanceCategoriesRoute: AuthenticatedFinanceCategoriesRoute,
  AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
  AuthenticatedFinanceIncomeRoute: AuthenticatedFinanceIncomeRoute,
  AuthenticatedFinanceReportsRoute: AuthenticatedFinanceReportsRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
